USE [master]
GO


CREATE DATABASE [PruebaKevinForero]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PruebaKevinForero', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\PruebaKevinForero.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PruebaKevinForero_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\PruebaKevinForero_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PruebaKevinForero] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PruebaKevinForero].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PruebaKevinForero] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET ARITHABORT OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PruebaKevinForero] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PruebaKevinForero] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PruebaKevinForero] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PruebaKevinForero] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PruebaKevinForero] SET  MULTI_USER 
GO

ALTER DATABASE [PruebaKevinForero] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PruebaKevinForero] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PruebaKevinForero] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PruebaKevinForero] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PruebaKevinForero] SET  READ_WRITE 
GO


